// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ingcqadwsbekyjmwfxpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZ2NxYWR3c2Jla3lqbXdmeHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjMyMzEsImV4cCI6MjA2MzgzOTIzMX0.gLVHiHIQnwl5OFMHyYmHdKNNiSz4841mBX7h8TUmqIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);